### ISSUE TITLE
how do i actually  get it onto my calculator?

### ISSUE THREAD

**Issue by Skulcrusherr** [TheScienceElf/Blocks-TI-84#13]
ipt just tells me:

a token in blocks is invalid, so we are not able to open it.

and 

sorry, it appears that clibs is broken

**Comment by Bee4Queer** [comment]
You need to first download clibs from [here](https://github.com/CE-Programming/libraries/releases/tag/v11.2)(like it says in the README instructions, you should have read them) and copy them on as well as prgmBLOCKS.

**Comment by Bee4Queer** [comment]
> You need to first download clibs from [here](https://github.com/CE-Programming/libraries/releases/tag/v11.2)(like it says in the README instructions, you should have read them) and copy them on as well as prgmBLOCKS.

Hello @Skulcrusherr? Did it work? If so, close the issue.

**Comment by Bee4Queer** [comment]
> > You need to first download clibs from [here](https://github.com/CE-Programming/libraries/releases/tag/v11.2)(like it says in the README instructions, you should have read them) and copy them on as well as prgmBLOCKS.
> 
> Hello @Skulcrusherr? Did it work? If so, close the issue.

@Skulcrusherr???? Close the issue if it worked!

**Comment by Bee4Queer** [comment]
Thank you.
