### ISSUE TITLE
Thoughts, Opinions and Ideas.

### ISSUE THREAD

**Issue by Axylotl** [TheScienceElf/Blocks-TI-84#15]
I will split this into two parts, my love for this port to the TI-84 and then some questions I have regarding its capability.

I absolutely love the way this is built. I love being able to mess around with the basic features of Minecraft and still have most the essential gameplay. I have already come really close to filling a full flat world with structures and stuff. However, now I have some questions regarding potential added capabilities that could be added.

**Would it be theoretically possible to create an update that allows for angle changes?** 
I like the way that roller coaster tycoon classic solves this issue on the phone version. They allow you to click a little arrow to change/rotate the world screen by 90 degrees. So four rotations allows for a full "360" turning. I was wondering if such a future could be added to the calculator port by using the parentheses buttons "(" and ")" to turn left and right. I think that adding this future would allow for more building options as currently everything I build has to be open ended and also work to not over shadow the other things I build. While I am not sure that this would directly solve the problem, I do think it would help especially with getting the most out of the available space given. I know that the amount of code and spacing is limited, but I was thinking this might be a small enough change to be implemented. 

**I would also want to know if deleting or overriding save files is or could be implemented?** 
I have a world currently that is a standard file but I realized there is no current way to remove or restart a world. This would be a very nice future that would allow me to remove old files and start fresh. 

**Also, how would I be able to access the source code?** 
I am really interested in being able to see the way this was developed and how everything is built. 

**Is there a community forum for this project that already exists that I am unaware of?** 
I was looking for one but I couldn't find anything.

Thanks for your help!

**Comment by commandz0** [comment]
> I would also want to know if deleting or overriding save files is or could be implemented?
> I have a world currently that is a standard file but I realized there is no current way to remove or restart a world. This would be a very nice future that would allow me to remove old files and start fresh.

Save files are stored in appvars, which you can delete from the calculator's memory menu (2nd+mem, 2, alpha+B).

> Also, how would I be able to access the source code?
> I am really interested in being able to see the way this was developed and how everything is built.

It's in this repo; you can access it from the "Code" tab.

**Comment by TheScienceElf** [comment]
I'm glad you're enjoying the project!

> Would it be theoretically possible to create an update that allows for angle changes?

I've gotten this one a lot. Theoretically yes, but it would require the entire tri-grid to be refreshed and the whole screen to be redrawn. Not impossible, but it would be a little slow. Plus, things like shadows and block textures wouldn't rotate accurately without some adjustments. I may experiment with this at some point, but it's not a high priority.

> I would also want to know if deleting or overriding save files is or could be implemented?

Forgot to mention this one in the README. You can delete worlds by putting the cursor over them in the world select menu and pressing the delete key.
