### ISSUE TITLE
Won't Run

### ISSUE THREAD

**Issue by vhh-1** [TheScienceElf/Blocks-TI-84#3]
Maybe i'm doing something wrong, but installed the library and the binary via connect Ce, and when I run via the program menu, it says ERROR: INVALID Attempted to use a variable or function where it is not valid. Help pls.

**Comment by adriweb** [comment]
Follow the instructions here https://yvantt.github.io/arTIfiCE/

**Comment by aquamarine-axo** [comment]
You need to install the arTIfiCE jailbreak as described above. You can use it to install another shell, like Cesium for example, to easily launch non-BASIC programs without having to go through arTIfiCE.

**Comment by Bee4Queer** [comment]
> You need to install the arTIfiCE jailbreak as described above. You can use it to install another shell, like Cesium for example, to easily launch non-BASIC programs without having to go through arTIfiCE.

And you can also use Asmhook to run them from the program menu.

**Comment by Bee4Queer** [comment]
Hello? Did these steps help? If so, please close the issue.
