### ISSUE TITLE
Bad token

### ISSUE THREAD

**Issue by LevelWilson** [TheScienceElf/Blocks-TI-84#4]
I've never had this issue before but I cant get to code to upload to my calculator. TI-84 Plus CE MacOS.

**Comment by adriweb** [comment]
You need to drag'n'drop the 8xp file onto the calculator name in the sidebar, not elsewhere otherwise TI-Connect CE will try to "open" it, which it can't because it's an ASM program.

**Comment by LevelWilson** [comment]
Thanks I forgot you could do that

**Comment by Bee4Queer** [comment]
Please close this issue if it got fixed.
