### ISSUE TITLE
Sometimes, saving either crashes on a blue screen, or must garbage collect.

### ISSUE THREAD

**Issue by ScottN13** [TheScienceElf/Blocks-TI-84#5]
Sadly could not replicate it now, but it did for once.

**Comment by CommentedNewline** [comment]
If you can't replicate it then "sometimes" may be the wrong word. XD
GarbageCollect is normal due to the massive amount of ram this program requires.

**Comment by ScottN13** [comment]
It happens from time to time, but at the time of opening the ticket, it didn't do so.

**Comment by ScottN13** [comment]
It happens from time to time, but at the time of opening the ticket, it didn't do so.

**Comment by ScottN13** [comment]
resovled: data overflow cause of towers ig
