### ISSUE TITLE
How I can run it without calculator (just with my laptop)?

### ISSUE THREAD

**Issue by white-echidna** [TheScienceElf/Blocks-TI-84#6]
Could you please add cmake support for this project? It's really interesting to try, but I couldn't because I dont have calculator

**Comment by adriweb** [comment]
This uses dedicated functions and features of the calculator, so it wouldn't run natively anywhere else, regardless of cmake vs make

**Comment by Bee4Queer** [comment]
If you want, you can use CEmu(https://ce-programming.github.io/CEmu/) to emulate a calculator, although you still need to get a ROM dump of a calculator.

**Comment by white-echidna** [comment]
Ye, I see that. Ok, I'll try to port it on PC

**Comment by Bee4Queer** [comment]
> Ye, I see that. Ok, I'll try to port it on PC

Good luck. I'd also suggest closing the issue since your working on it.

**Comment by white-echidna** [comment]
ok, thanks
