### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by 1qrobo1** [TheScienceElf/Blocks-TI-84#8]
I have the two libraries installed but it it says invalid library. Does anyone have the same problem or solution?

**Comment by 1qrobo1** [comment]
Wait it says error library version but all my other games use clibs and it is fine and I have the newest version

**Comment by adriweb** [comment]
Well the latest libs are from a few days ago only: https://github.com/CE-Programming/libraries/releases/latest
Does that work better?

**Comment by 1qrobo1** [comment]
No

**Comment by 1qrobo1** [comment]
> Well the latest libs are from a few days ago only: https://github.com/CE-Programming/libraries/releases/latest
> 
> Does that work better?

No

**Comment by adriweb** [comment]
How about those? https://github.com/CE-Programming/toolchain/releases/download/nightly/clibs-nightly.8xg

(technically the same, but who knows. Make sure all the libs are transfered, it won't be the case with ti connect ce for chromeOS... which is why you'd need to use the zip from the link I posted above)

**Comment by YEETMaster86** [comment]
make sure you replace all duplicate files, as this is updating the existing files if you already have an older version of clibs installed

**Comment by 1qrobo1** [comment]
> How about those? https://github.com/CE-Programming/toolchain/releases/download/nightly/clibs-nightly.8xg
> 
> (technically the same, but who knows. Make sure all the libs are transfered, it won't be the case with ti connect ce for chromeOS... which is why you'd need to use the zip from the link I posted above)

it says libary version

**Comment by 1qrobo1** [comment]
as the error

**Comment by Bee4Queer** [comment]
> as the error

Can you provide a screenshot/the _exact_ error?

**Comment by 1qrobo1** [comment]
It is fixed I used the separate zip file and it launched
