### ISSUE TITLE
does not run

### ISSUE THREAD

**Issue by red3racer** [TheScienceElf/Blocks-TI-84#9]
i downloaded everything and it says not enough memory i deleted every program and it still says that

**Comment by adriweb** [comment]
1. Make sure you're on OS 5.3.0 or later (if possible, less than 5.5, otherwise you'll need arTIfiCE).
2. Backup/archive any variables you care about
3. Press and hold the RESET button on the back for 3-4s
4. Try the program again

**Comment by red3racer** [comment]
i tried that and still does not have enough memory is it about how much ram is free? cuz i only have 34k left for the program to run

**Comment by adriweb** [comment]
if you have OS 5.3 or later, you don't need to have programs in RAM to run them (but you need that if you want to edit them if they're TI-Basic), so archive all of them then try again

**Comment by AverseABFun** [comment]
I had this same problem, just archive the program itself(Archive prgmBLOCKS) and try again

**Comment by red3racer** [comment]
> I had this same problem, just archive the program itself(Archive prgmBLOCKS) and try again

thank you this made it work :)

**Comment by AverseABFun** [comment]
> > I had this same problem, just archive the program itself(Archive prgmBLOCKS) and try again
> 
> thank you this made it work :)

Glad to help :) Now close the issue as it was fixed.

**Comment by AverseABFun** [comment]
> > > I had this same problem, just archive the program itself(Archive prgmBLOCKS) and try again
> > 
> > 
> > thank you this made it work :)
> 
> Glad to help :) Now close the issue as it was fixed.

Be sure to close this issue, like I said.

**Comment by AverseABFun** [comment]
> > > > I had this same problem, just archive the program itself(Archive prgmBLOCKS) and try again
> > > 
> > > 
> > > thank you this made it work :)
> > 
> > 
> > Glad to help :) Now close the issue as it was fixed.
> 
> Be sure to close this issue, like I said.

Close the issue, this is your third reminder.

**Comment by AverseABFun** [comment]
Please close the issue!

**Comment by commandblockguy** [comment]
> Please close the issue!

There's zero harm in the issue being left open. On the other hand, the repeated emails I'm getting from your reminders are rather annoying and are only adding useless noise to the thread.

**Comment by AverseABFun** [comment]
Sorry, I just have a pet peeve for issues left open, and you could have at
least said that earlier. Plus, the literal point of closing issues is for
things that have either been fixed or solved, or things that aren't planned.

**Comment by red3racer** [comment]
How do I close it I’m sorry for it being open this long

**Comment by AverseABFun** [comment]
Thanks, you just press the close button on the GitHub page. In the email,
you can press "view on GitHub" and then scroll down and press close.
